### PR TITLE
Pass jest with no tests

### PR DESCRIPTION
**Pull request by chrispiccaro18**
This will allow master branches to pass Travis.

### CODE REVIEW

**Comment by mehtaphysical** [comment]
But shouldn't there always be tests?

**Comment by chrispiccaro18** [comment]
Master doesn't have any tests and gets a big, fat, red 'X'!

**Comment by chrispiccaro18** [comment]
Would it be better to add a test that passes?

**Comment by mehtaphysical** [comment]
Yeah add a hello world App.js and snapshot test! Thanks!

**Pull request closed without merging**
